/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20 from './erc-20';
export type { erc20 };
import type * as erc721 from './erc-721';
export type { erc721 };
import type * as service from './service';
export type { service };
