name: Duzzle Dev API Server Deployment
on:
  push:
    branches: [ dev ]

  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Add Droplet to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Sync files via rsync
        run: |
          rsync -avz --delete --exclude='env/.env.dev' ./ ${{ secrets.DO_SSH_USER }}@${{ secrets.DROPLET_IP }}:/home/${{ secrets.DO_SSH_USER }}/duzzle-be

      - name: Install dependencies, build and start application
        run: |
          ssh ${{ secrets.DO_SSH_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
          cd /home/${{ secrets.DO_SSH_USER }}/duzzle-be
          npm install
          npm run build NODE_ENV=dev
          nohup npm run start > /dev/null 2>&1 &
          EOF

        env:
          SSH_USER: ${{ secrets.DO_SSH_USER }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
